.TH MFILER4 1
.SH NAME
mfiler4
a console based file manager

.SH SYNOPSIS
.Nm mfiler4
[-c command] [--version] [ filer initial directory or script file ]

.SH DESCRIPTION
a two pane console based file manager.

The following options are available
.Pp
\-c " string"
.br
Commands described by string are executed and exit immediately.
.Pp
\-s

.SH USAGE
run mfiler4 and hit ? key

.SH COPYRIGHT
Copyright 2012 by ab25cq

